[tool.briefcase]
project_name = "Twitter Analysis App"
bundle = "com.twitter-analysis-app"
version = "1.0.1"
url = "https://dataforgoodmad.com/"
license = "GNU General Public License v3 or later (GPLv3+)"
author = 'César Castañón - Data For Good Madrid'
author_email = "cesar.castares@gmail.com"

[tool.briefcase.app.twitter-analysis-app]
formal_name = "Twitter Analysis App"
description = ""
icon = "src/twitter_analysis_app/resources/dataforgoodmad-logo"
sources = ['src/twitter_analysis_app']
requires = []


[tool.briefcase.app.twitter-analysis-app.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.twitter-analysis-app.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.twitter-analysis-app.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.twitter-analysis-app.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.twitter-analysis-app.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
